apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
    spec:
      containers:
      - name: pub-app
        image: ghcr.io/mgelei/pub-sandbox:latest