apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-sandbox
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub-sandbox
  template:
    metadata:
      labels:
        app: pub-sandbox
    spec:
      containers:
        - name: pub-sandbox
          image: ghcr.io/mgelei/pub-sandbox:latest
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: ghcr-login-secret