apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-sandbox
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-sandbox
  template:
    metadata:
      labels:
        app: sub-sandbox
    spec:
      containers:
        - name: sub-sandbox
          image: ghcr.io/mgelei/sub-sandbox:latest
          imagePullPolicy: IfNotPresent