name: Deploy apps
on:
  push:
    branches:
      - master
    paths:
      - 'pub-app/**'
      - 'sub-app/**'
      - 'helm/**'
  workflow_dispatch:

jobs:
  pub-build: # These two jobs are nearly identical, might want to merge them to a matrix
    runs-on: ubuntu-22.04
    name: Build Docker image
    concurrency:
      group: pub-build
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy requirements.txt
        run: cp requirements.txt ./pub-app/
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./pub-app/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pub-sandbox:latest

  sub-build:
    runs-on: ubuntu-22.04
    name: Build Docker image
    concurrency:
      group: sub-build
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy requirements.txt
        run: cp requirements.txt ./sub-app/
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./sub-app/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sub-sandbox:latest

  helm:
    needs: [pub-build, sub-build]
    runs-on: ubuntu-22.04
    name: Deploy apps
    environment: prod
    concurrency:
      group: helm
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Helm
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Inject kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Install/upgrade project
        run: helm upgrade --install pubsub ./helm