name: Deploy Producer
on:
  push:
    branches:
      - master
    paths:
      - 'pub-app/**'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    name: Build Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./pub-app
          push: true
          tags: mgelei/pub-sandbox:latest